#!/bin/bash

APP='realty-ui'
CMD=$1

case $APP in
  "build")
    docker build -t $APP .
    ;;
  "run")
    docker run -d -p 80:80 --name $APP $APP
    ;;
  "start")
    docker start $APP
    ;;
  "stop")
    docker stop $APP
    ;;
  "attach")
    docker start -a $APP
    ;;
  "restart")
    docker restart $APP
    ;;
  "eject")
    docker rm $APP
    ;;
  "compose")
    docker compose up --build
    ;;
  "uncompose")
    docker compose down
    ;;
  *)
    echo "Invalid command"
    ;;
esac
